controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.24
    wheel_radius: 0.05

    # Odometry covariances for the encoder output of the robot
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    # Top level frame (link) of the robot description
    base_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 50.0
    
    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5  # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2

    # Controller parameters
    position_feedback: false
    cmd_vel_timeout: 0.5  # seconds
    publish_limited_velocity: true
    use_stamped_vel: false