ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    use_tf_static: true
    debug: true
    debug_out_file: /home/sigma/unibots/debug_ekf.txt
    
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # IMU configuration
    imu0: /imu/drift_corrected
    imu0_frame_id: bno055
    imu0_config: [true, true, true,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  true, true, true]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    # imu0_remove_gravitational_acceleration: true

    imu0_nodelay: false
    
    # Debug diagnostics
    print_diagnostics: true