controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.17  # meters (adjust to your robot's wheel separation)
    wheel_radius: 0.033     # meters (adjust to your robot's wheel radius)
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    
    open_loop: true
    enable_odom_tf: true
    
    cmd_vel_topic: "cmd_vel"
    use_stamped_vel: false
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5       # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0   # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0       # rad/s
        has_acceleration_limits: true
        max_acceleration: 4.0   # rad/s^2

tb6612fng_hardware:
  plugin: robot_control_py/DummyHardwareInterface
  ros__parameters:
    gpio_chip: "gpiochip4"
    
    # Left wheel motor pins
    left_in1_pin: 8
    left_in2_pin: 7
    left_pwm_pin: 12
    
    # Right wheel motor pins
    right_in1_pin: 23
    right_in2_pin: 24
    right_pwm_pin: 13
    
    # Standby pin (shared between motors)
    standby_pin: 25
    
    # Motor configurations
    left_reversed: true
    right_reversed: false
    
    # Max velocity that corresponds to 100% duty cycle
    max_velocity: 10.0  # rad/s